source 'https://rubygems.org'
gem 'rails', '4.2.1'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml-rails'
gem 'mini_magick'
gem 'kaminari'
gem 'carrierwave', '0.10.0'
gem 'fog'
gem 'unf'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'rspec', '3.3.0'
  gem 'rspec-rails', '3.3.3'
  gem 'factory_girl_rails'
end
